### PR TITLE
fix: default class formatting

### LINKED ISSUE #108: Default icon doesn't count as an icon for styling
```
[format]
client = "{icon}"
client_active = "<span color='#ff4040'>{icon}</span>"
[class]
DEFAULT = ""
```

Set this as your config, you'll notice the default icon doesn't reflect the changes made to the span color there, because it doesn't count as an icon for some reason.

### PR DESCRIPTION
**Pull request by matt-fff**
## Description

Default class strings did not respect active formatting configurations. This is because the pattern matcher that applies formatting only does so if the client is simultaneously [active and with an inactive matched rule](https://github.com/hyprland-community/hyprland-autoname-workspaces/blob/ba126d55bccfbfbf7dd461b72e617796192693cc/src/renamer/formatter.rs#L85).

There was a bug with inactive default rules that caused them to [always be marked as active when the client was active](https://github.com/hyprland-community/hyprland-autoname-workspaces/blob/ba126d55bccfbfbf7dd461b72e617796192693cc/src/renamer/icon.rs#L216-L218).

This PR ensures that inactive default rules are evaluated as inactive even when the client is currently active - allowing formatting to be applied.

Fixes #108 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

New unit test added. Tested default class formatting behavior on my local system.

### CODE REVIEW

File: src/renamer/icon.rs [hunk 1]
```diff
@@ -28,11 +28,6 @@ impl IconConfig {
         icon
     }
 
-    pub fn rule(&self) -> Rule {
-        let (rule, _, _) = self.get();
-        rule
-    }
-
```
Comment (matt-fff) [inline src/renamer/icon.rs:35]: Newly dead code

File: src/renamer/icon.rs [hunk 2]
```diff
@@ -213,9 +202,7 @@ impl Renamer {
         let icon_default_active = self
             .find_icon("DEFAULT", "DEFAULT", "", "", true, config)
             .unwrap_or({
-                self.find_icon("DEFAULT", "DEFAULT", "", "", false, config)
-                    .map(|i| Active(Class(i.rule(), i.icon())))
-                    .unwrap_or(Active(Default("no icon".to_string())))
+                icon_default.clone()
```
Comment (matt-fff) [inline src/renamer/icon.rs:205]: Just reuse the inactive default we already acquired.

**Review by cyrinux — APPROVED** [review]
